"""Adding date/time column for existing DB tables.

Revision ID: 2c9366de1404
Revises: 3fb7427ddc46
Create Date: 2026-01-11 21:40:41.376460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9366de1404'
down_revision: Union[str, Sequence[str], None] = '3fb7427ddc46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation_requests', sa.Column('translation_date', sa.DateTime(), server_default=sa.text('getutcdate()'), nullable=False))
    op.alter_column('usage_data', 'usage_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage_data', 'usage_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_column('translation_requests', 'translation_date')
    # ### end Alembic commands ###
