"""Initial migration

Revision ID: 3fb7427ddc46
Revises: 
Create Date: 2026-01-11 21:22:46.113485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fb7427ddc46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=True),
    sa.Column('text_to_translate', sa.String(length=4000), nullable=False),
    sa.Column('original_text_language', sa.String(length=10), nullable=False),
    sa.Column('translated_text', sa.String(length=4000), nullable=False),
    sa.Column('target_text_language', sa.String(length=10), nullable=False),
    sa.Column('is_success_request', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_requests_id'), 'translation_requests', ['id'], unique=False)
    op.create_table('usage_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('model_company', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=40), nullable=False),
    sa.Column('input_calculated_token_count', sa.Integer(), nullable=True),
    sa.Column('input_token_count', sa.Integer(), nullable=False),
    sa.Column('output_token_count', sa.Integer(), nullable=False),
    sa.Column('total_token_count', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_data_id'), 'usage_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_data_id'), table_name='usage_data')
    op.drop_table('usage_data')
    op.drop_index(op.f('ix_translation_requests_id'), table_name='translation_requests')
    op.drop_table('translation_requests')
    # ### end Alembic commands ###
